# Generated by Django 5.0.6 on 2024-06-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0003_customuser_phone_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
