# Generated by Django 5.0.6 on 2024-07-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0008_product_is_approved_alter_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_handled',
            field=models.BooleanField(default=False),
        ),
    ]
